name: CI

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    audit:
        runs-on: ubuntu-slim
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v7
            - uses: flatt-security/setup-takumi-guard-npm@v1
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun audit

    lint:
        runs-on: ubuntu-slim
        permissions:
            contents: read
        steps:
            - uses: actions/checkout@v7
            - uses: flatt-security/setup-takumi-guard-npm@v1
            - uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest
            - run: bun install
            - run: bun run lint
